### ISSUE TITLE
Scraping job data

### ISSUE THREAD

**Issue by Thaslim42** [mendableai/firecrawl#602] opened 2024-09-02 06:08 UTC
while i used firecrawl to scrape data from a job site it only scraped data from the initial page. but the actual data is present inside the job title link i wanted to extract that data too how can i achievev it? ...here is a sample screenshot of the page
![info](https://github.com/user-attachments/assets/cf39bf8d-8ea0-4925-9436-ad808a1a9a6c)

**Comment by nickscamara** [comment] 2024-09-03 02:39
Hey @Thaslim42 could you try running with `allowBackwardLinks` option? This enables the crawler to navigate from a specific URL to previously linked pages or pages that are not children of the one that you started the crawl.

**Comment by Thaslim42** [comment] 2024-09-03 11:25
it still dont worked..any other options?

**Comment by nickscamara** [comment] 2024-09-04 15:14
@Thaslim42 

ccing @tomkosm

**Comment by tomkosm** [comment] 2024-09-06 11:49
@Thaslim42 are you using scrape or crawl? You should use crawl for this, please share all of the options you are using, the url and the result you are getting. Also are you running self host or using the api?

**Comment by Thaslim42** [comment] 2024-09-13 06:39
i used firecrawl playground to crawl this url  and it only scraped links of unwanted contents like newsletter gallary etc..but the content inside the job title link didnt scarped...here is a ss of params i provided
![Screenshot 2024-09-13 120912](https://github.com/user-attachments/assets/def36093-72c3-4da6-bbe0-ba98eb2cb92a)

**Comment by rafaelsideguide** [comment] 2024-10-18 17:15
Hey @Thaslim42, It looks like the issue is with the URL you're trying to scrape. The page only exists with the "www" in the address, like this: https://www.infopark.in/companies/jobs/thrissur. The server seems to have a DNS issue where it can't find the page without "www". You should be able to resolve this by adding "www" to the URL and using the `allowBackwardLinks` option.

Let me know if this helps! I'm closing this issue for now, but feel free to reopen it if needed.

**Closed by rafaelsideguide** 2024-10-18 17:15 UTC
Labels: question
